[package]
name = "shellcode-loader"
version = "0.1.0"
edition = "2021"
authors = ["Satria Ady Pradana <xathrya@reversing.id>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.151"
mmap = "0.1.1"
